services:
  - type: static_site
    name: FarmDirect-1
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://farmdirect-weez.onrender.com/api
    routes:
      - path: /*
        destination: /index.html
